/**
 * @author sh: -c: line 1: syntax error: unexpected end of file (2)
 */

// Generated by CoffeeScript 1.6.3
var validerFormulaire, verifChamp;

verifChamp = function(champ, erreur) {
    if (erreur) {
        champ.style.backgroundColor = "#FF0000";
        return false;
    } else {
        champ.style.backgroundColor = "#FFFFFF";
        return true;
    }
};



validerFormulaire = function() {
    var formatCodeMS, formatMotDePasse, codeMS, passW, radioEtudiant, radioProf, radioDemo;
    formatMotDePasse = new RegExp("^[a-zA-Z]{4}[0-9]{5}$", "g");
    formatCodeMS = new RegExp("^[a-zA-Z]{2}[0-9]{6}$", "g");


    codeMS = document.getElementById("codeMS");
    passW = document.getElementById("passW");

    radioEtudiant = document.getElementById("radioEtudiant");
    radioProf = document.getElementById("radioProf");
    radioDemo = document.getElementById("radioDemo");





    if (codeMS.value === "") {
        verifChamp(document.formulaire.username, true);
        alert("Le champ code MS doit être rempli.");
        return false;
    } else {
        verifChamp(document.formulaire.username, false);
    }

    if (passW.value === "") {
        verifChamp(document.formulaire.password, true);
        alert("Le champ mot de passe doit être rempli.");
        return false;
    } else {
        verifChamp(document.formulaire.password, false);
    }


    if (!formatCodeMS.test(codeMS.value)) {
        verifChamp(document.formulaire.username, true);
        alert("Le champ code MS doit être composé de 2 lettres suivies de 6 chiffres.");
        return false;
    } else {
        verifChamp(document.formulaire.username, false);
    }


    if (!formatMotDePasse.test(passW.value)) {
        verifChamp(document.formulaire.password, true);
        alert("Le champ mot de passe doit être composé de 4 lettres suivies de 5 chiffres.");
        return false;
    } else {
        verifChamp(document.formulaire.password, false);
    }

    if (radioEtudiant.checked == false)
    {
        alert("Vous devez selectionner une categorie: Etudiant ou Professeur ou Demonstrateur.");
        return false;
    } else
    {

        return true;
    }

};

validerReponse = function() {


    //for (i = 0 ; i < 2 ; i++) {
    if (document.formulaire.radio[0].cheked) {
        alert('Réponse fausse.');
        location.href = 'etudiant.html';
        //return true;
    }
    if (document.formulaire.radio[1].cheked) {
        location.href = 'enseignant.html';

    }
    if (document.formulaire.radio[2].cheked) {
        location.href = 'demonstrateur.html';

    }
    //}
};

